version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/target
    
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_server
      timeout: 300
      runas: root